# app.py
"""
Rewritten Streamlit frontend (simplified Optimize page).

Key changes:
- Optimize page simplified: removed template style, preview PDF toggle, Overleaf.
- Optimize page now shows:
  - Full optimized text (single block)
  - Section-wise blocks (Summary, Experience, Skills, Education) as editable textareas
  - Copy buttons for each section (helper notification to copy manually)
  - Download buttons for TXT and PDF (if PDF exists or can be generated by rewriter)
- Keeps DB, thumbnail creation, parser/analyzer/scorer, rewriter fallbacks.
- Uses developer-provided uploaded path: /mnt/data/ROHAN_CHAVAN.pdf
"""

import streamlit as st
import json
import sqlite3
import pandas as pd
import numpy as np
from datetime import datetime
import plotly.express as px
import base64
import os
import io
from typing import Dict, Any, Optional, List

# Optional libs for thumbnails
try:
    from PIL import Image, ImageDraw, ImageFont
except Exception:
    Image = None

# Try importing backend modules; provide simple fallbacks if absent
try:
    from parser import ResumeParser  # type: ignore
    from analyzer import ResumeAnalyzer  # type: ignore
    from scorer import ATSScorer  # type: ignore
    from rewriter import ResumeRewriter  # type: ignore
    BACKEND_AVAILABLE = True
except Exception:
    BACKEND_AVAILABLE = False

    class ResumeParser:
        def parse_resume(self, uploaded_file):
            return {
                "filename": getattr(uploaded_file, "name", "uploaded_resume.pdf"),
                "text": "Demo parsed resume text. Replace parser with real module to get actual output.\n\nExperience:\n- Built demo project.",
                "contact_info": {"email": "demo@example.com", "phone": "+91-XXXXXXXX", "name": "Demo User", "location": "City, Country"},
                "skills": ["Python", "Machine Learning", "NLP", "SQL"],
                "education": []
            }

    class ResumeAnalyzer:
        def analyze_resume(self, parsed_data: Dict[str, Any]):
            return {
                "layout_score": 0.68,
                "sections": ["Summary", "Experience", "Education"],
                "issues": [],
                "tfidf": 0.58,
            }

    class ATSScorer:
        def compute_ats_score(self, parsed_resume, job_description, analysis_results):
            return {
                "final_score": 0.67,
                "sbert_score": 0.65,
                "tfidf_score": 0.58,
                "layout_score": float(analysis_results.get("layout_score", 0.5)),
                "missing_skills": ["Kubernetes", "AWS"],
                "matching_skills": parsed_resume.get("skills", [])[:5],
                "recommendations": ["Add measurable achievements", "Include relevant keywords"]
            }

    class ResumeRewriter:
        def rewrite_resume(self, parsed_resume, job_description, ats_scores, sections=None, style=None):
            # Minimal demo improved summary + latex generation
            text = parsed_resume.get("text", "")
            improved_summary = "Experienced professional with strong technical skills and proven impact."
            # Provide per-section keys to keep compatibility
            return {
                "text": text + "\n\n[Optimized Summary]\n" + improved_summary,
                "pdf_path": None,
                "improvements": ["Improved summary (demo)"],
                "summary_optimized": improved_summary,
                "experience_optimized": parsed_resume.get("text", ""),
                "skills_optimized": ", ".join(parsed_resume.get("skills", [])),
                "education_optimized": ""
            }
        def generate_pdf(self, optimized_resume, style):
            return optimized_resume.get("pdf_path")  # demo

# Paths & constants
DB_PATH = "resume_data.db"
THUMB_DIR = "thumbnails"
os.makedirs(THUMB_DIR, exist_ok=True)

# Convenience: uploaded file path from developer message (useful for local testing)
UPLOADED_FILE_PATH = "/mnt/data/ROHAN_CHAVAN.pdf"

# Streamlit config
st.set_page_config(page_title="AI Resume Analyzer — Simplified Optimize", page_icon="📄", layout="wide")

# --------------------------- Utility functions ----------------------------

def ensure_db():
    """Create DB and add optional columns if missing."""
    conn = sqlite3.connect(DB_PATH, check_same_thread=False)
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS resume_analysis (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            filename TEXT,
            upload_date TEXT,
            ats_score REAL,
            layout_score REAL,
            tfidf_score REAL,
            sbert_score REAL,
            missing_skills TEXT,
            extracted_entities TEXT,
            analysis_results TEXT
        )
    ''')
    conn.commit()
    # add optional columns: job_title, thumbnail_path, skills, latex (if not exists)
    existing_cols = [row[1] for row in cursor.execute("PRAGMA table_info(resume_analysis)").fetchall()]
    optional_additions = {
        "job_title": "ALTER TABLE resume_analysis ADD COLUMN job_title TEXT",
        "thumbnail_path": "ALTER TABLE resume_analysis ADD COLUMN thumbnail_path TEXT",
        "skills": "ALTER TABLE resume_analysis ADD COLUMN skills TEXT",
        "latex": "ALTER TABLE resume_analysis ADD COLUMN latex TEXT"
    }
    for col, query in optional_additions.items():
        if col not in existing_cols:
            try:
                cursor.execute(query)
                conn.commit()
            except Exception:
                pass
    conn.close()

def numpy_safe(obj):
    """Recursively convert numpy types to Python native so JSON serialization works."""
    if isinstance(obj, dict):
        return {k: numpy_safe(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [numpy_safe(v) for v in obj]
    if isinstance(obj, (np.floating, np.float32, np.float64)):
        return float(obj)
    if isinstance(obj, (np.integer,)):
        return int(obj)
    return obj

def json_dumps_safe(obj):
    """Serialize object to JSON safely (converting numpy types)."""
    try:
        return json.dumps(numpy_safe(obj), default=str)
    except Exception:
        return json.dumps(str(obj))

def create_download_link_bytes(bytes_data: bytes, filename: str, label: str = "Download"):
    b64 = base64.b64encode(bytes_data).decode()
    href = f'<a href="data:application/octet-stream;base64,{b64}" download="{filename}" style="padding:8px 12px;background:linear-gradient(90deg,#7b39ff,#9f6bff);color:white;border-radius:8px;text-decoration:none">{label}</a>'
    return href

def create_text_thumbnail(text: str, out_path: str, width=400, height=260):
    """Create a simple text-based thumbnail using Pillow fallback."""
    if Image is None:
        return None
    try:
        img = Image.new("RGB", (width, height), (19, 10, 30))
        draw = ImageDraw.Draw(img)
        try:
            font = ImageFont.truetype("arial.ttf", 13)
        except Exception:
            font = ImageFont.load_default()
        # Compose preview text: first 600 chars, wrapped
        txt = " ".join(text.strip().split())
        txt = txt[:800]
        words = txt.split(" ")
        lines = []
        line = ""
        for w in words:
            if len(line) + len(w) + 1 > 45:
                lines.append(line.strip())
                line = w
            else:
                line = (line + " " + w).strip()
        if line:
            lines.append(line.strip())
        y = 10
        color = (235, 226, 255)
        for ln in lines[:12]:
            draw.text((10, y), ln, font=font, fill=color)
            y += 18
        img.save(out_path, quality=75)
        return out_path
    except Exception:
        return None

# --------------------------- DB save/load ----------------------------

def save_analysis_to_db(scores: Dict[str, Any], parsed_resume: Optional[Dict] = None, filename: str = "uploaded_resume.pdf", job_title: Optional[str]=None):
    """Save scores and optional parsed resume data. Convert numpy types to native."""
    ensure_db()
    try:
        conn = sqlite3.connect(DB_PATH, check_same_thread=False)
        cursor = conn.cursor()
        # prepare fields
        ats_score = float(scores.get("final_score", 0) or 0)
        layout_score = float(scores.get("layout_score", 0) or 0)
        tfidf_score = float(scores.get("tfidf_score", 0) or 0)
        sbert_score = float(scores.get("sbert_score", 0) or 0)
        missing_skills = json_dumps_safe(scores.get("missing_skills", []))
        analysis_results = json_dumps_safe(scores)
        skills_json = None
        thumbnail = None
        latex = scores.get("latex") or None
        if parsed_resume:
            sk = parsed_resume.get("skills")
            if sk:
                skills_json = json_dumps_safe(sk)
            text = parsed_resume.get("text", "")
            # create thumbnail (cache)
            safe_name = filename.replace("/", "_").replace("\\", "_")
            thumb_path = os.path.join(THUMB_DIR, f"{safe_name}.jpg")
            if text and (not os.path.exists(thumb_path)):
                t = create_text_thumbnail(text, thumb_path)
                if t:
                    thumbnail = thumb_path
            elif os.path.exists(thumb_path):
                thumbnail = thumb_path

        cursor.execute('''
            INSERT INTO resume_analysis
            (filename, upload_date, ats_score, layout_score, tfidf_score, sbert_score, missing_skills, analysis_results, job_title, thumbnail_path, skills, latex)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ''', (
            filename,
            datetime.now().isoformat(),
            ats_score,
            layout_score,
            tfidf_score,
            sbert_score,
            missing_skills,
            analysis_results,
            job_title,
            thumbnail,
            skills_json,
            latex
        ))
        conn.commit()
        conn.close()
    except Exception as e:
        st.error(f"Error saving analysis to DB: {e}")

def load_all_analysis() -> pd.DataFrame:
    ensure_db()
    try:
        conn = sqlite3.connect(DB_PATH, check_same_thread=False)
        df = pd.read_sql_query("SELECT * FROM resume_analysis ORDER BY upload_date DESC", conn)
        conn.close()
        return df
    except Exception:
        return pd.DataFrame([])

# --------------------------- Rewriter helpers (formatting) ----------------------------

def clean_formatting(text: str) -> str:
    """Fix spacing, normalize bullets, tidy whitespace."""
    import re
    if not text:
        return ""
    text = text.replace("\r", "")
    # Normalize bullets to dash
    text = re.sub(r'[\u2022•]', '-', text)
    # collapse multiple blank lines
    text = re.sub(r'\n\s*\n+', '\n\n', text)
    # collapse multiple spaces
    text = re.sub(r' {2,}', ' ', text)
    # indent bullets
    text = re.sub(r'(?m)^\s*-\s*', '  - ', text)
    return text.strip()

# --------------------------- UI components ----------------------------

def display_metric_row(total: int, avg_ats: Optional[float], high_quality: int, this_week: int):
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total Resumes", total)
    c2.metric("Avg ATS Score", f"{avg_ats:.1%}" if avg_ats is not None and not pd.isna(avg_ats) else "N/A")
    c3.metric("High Quality (>=70%)", high_quality)
    c4.metric("This Week", this_week)

def display_preview_html(optimized: Dict[str, Any]):
    """Styled HTML preview for a quick top-level view."""
    name = optimized.get("name", "")
    contact = optimized.get("contact_info", {})
    email = contact.get("email", "")
    phone = contact.get("phone", "")
    location = contact.get("location", "")
    summary = optimized.get("summary_optimized") or optimized.get("summary", "")
    skills = optimized.get("skills", [])
    experience = optimized.get("experience_optimized") or optimized.get("experience", "")
    education = optimized.get("education_optimized") or optimized.get("education", "")

    html = f"""
    <div style="border-radius:10px;padding:14px;background:#fff;color:#111;border:1px solid #eee">
      <div style="display:flex;justify-content:space-between">
        <div>
          <div style="font-size:18px;font-weight:700">{name}</div>
          <div style="color:#666">{email} • {phone} • {location}</div>
        </div>
        <div style="background:linear-gradient(90deg,#7b39ff,#9f6bff);padding:8px 12px;border-radius:8px;color:white;font-weight:700">{optimized.get('final_score_display','')}</div>
      </div>
      <hr/>
      <div style="font-weight:700">Summary</div>
      <div style="white-space:pre-wrap;margin-top:6px">{summary}</div>
      <div style="display:flex;gap:20px;margin-top:10px">
        <div style="flex:1">
          <div style="font-weight:700">Skills</div>
          <div style="margin-top:6px">{', '.join(skills[:20])}</div>
        </div>
        <div style="flex:2">
          <div style="font-weight:700">Experience (excerpt)</div>
          <div style="margin-top:6px;white-space:pre-wrap">{experience[:900]}</div>
        </div>
      </div>
    </div>
    """
    st.markdown(html, unsafe_allow_html=True)

# --------------------------- Pages ----------------------------

def page_upload():
    st.title("Resume Upload & Parsing")
    st.write("Upload a PDF or DOCX resume. The parser will extract text, contact info, skills and sections.")
    uploaded_file = st.file_uploader("Upload resume (PDF/DOCX)", type=["pdf", "docx"])
    if uploaded_file is None:
        st.info("Upload a resume to get started.")
        return

    with st.spinner("Parsing..."):
        parser = ResumeParser()
        parsed = parser.parse_resume(uploaded_file)
        st.session_state.parsed_resume = parsed

    with st.spinner("Analyzing structure..."):
        analyzer = ResumeAnalyzer()
        analysis = analyzer.analyze_resume(parsed)
        st.session_state.analysis_results = analysis

    # show key info
    col1, col2 = st.columns([1, 1])
    with col1:
        st.subheader("Contact")
        contact = parsed.get("contact_info", {})
        for k, v in contact.items():
            st.write(f"**{k.title()}**: {v}")
        st.subheader("Skills")
        skills = parsed.get("skills", [])
        if skills:
            st.write(", ".join(skills[:50]))
        else:
            st.write("No skills detected.")
    with col2:
        st.subheader("Structure")
        st.metric("Layout compliance", f"{analysis.get('layout_score', 0.0):.1%}")
        if analysis.get("sections"):
            st.write("Sections detected:", ", ".join(analysis.get("sections")))

    st.subheader("Parsed Text Preview")
    st.text_area("Parsed text", parsed.get("text", ""), height=360)

def page_job_matching():
    st.title("Job Matching")
    if st.session_state.get("parsed_resume") is None:
        st.warning("Upload and parse a resume first.")
        return
    jd = st.text_area("Paste job description", height=260, value=st.session_state.get("job_description", ""))
    if st.button("Compute Match"):
        if not jd.strip():
            st.error("Enter a job description.")
        else:
            st.session_state.job_description = jd
            with st.spinner("Computing ATS scores..."):
                scorer = ATSScorer()
                scores = scorer.compute_ats_score(st.session_state.parsed_resume, jd, st.session_state.analysis_results or {})
                # ensure numpy safe
                scores = numpy_safe(scores)
                st.session_state.ats_scores = scores
                # Save to DB (include parsed resume for thumbnails/skills)
                save_analysis_to_db(scores, parsed_resume=st.session_state.parsed_resume, filename=st.session_state.parsed_resume.get("filename", "uploaded_resume.pdf"), job_title=jd[:120].replace("\n", " "))
            st.success("Done.")

    # Display scores if available
    if st.session_state.get("ats_scores"):
        s = st.session_state.ats_scores
        display_score = float(s.get("final_score", 0.0))
        st.subheader("Match Score")
        st.metric("ATS Score", f"{display_score:.1%}")
        col1, col2, col3 = st.columns(3)
        col1.metric("Semantic", f"{float(s.get('sbert_score', 0.0)):.1%}")
        col2.metric("Keyword", f"{float(s.get('tfidf_score', 0.0)):.1%}")
        col3.metric("Layout", f"{float(s.get('layout_score', 0.0)):.1%}")

        st.subheader("Skill Gap")
        colA, colB = st.columns(2)
        with colA:
            st.write("Missing")
            for item in s.get("missing_skills", [])[:30]:
                st.write(f"- ❌ {item}")
        with colB:
            st.write("Matched")
            for item in s.get("matching_skills", [])[:30]:
                st.write(f"- ✅ {item}")

        st.subheader("Recommendations")
        for r in s.get("recommendations", [])[:10]:
            st.write(f"- {r}")

def _save_text_file_and_get_path(text: str, out_name: str = "optimized_resume.txt") -> Optional[str]:
    """Create a UTF-8 text file and return its path."""
    try:
        out_path = out_name
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(text)
        return out_path
    except Exception:
        return None

def page_optimize():
    st.title("AI Resume Optimization")

    if st.session_state.get("parsed_resume") is None or st.session_state.get("ats_scores") is None:
        st.warning("Please parse a resume and compute job match first.")
        return

    st.write("Select sections to optimize:")
    sections = st.multiselect(
        "Sections",
        ["Experience", "Skills", "Summary", "Education"],
        default=["Experience", "Skills"]
    )


    if st.button("Generate Optimized Resume"):
        with st.spinner("Rewriting with AI..."):
            rewriter = ResumeRewriter()

            selected_sections = [s.lower() for s in sections]
            optimized = rewriter.rewrite_resume(
                st.session_state.parsed_resume,
                st.session_state.job_description,
                st.session_state.ats_scores,
                sections=selected_sections
            )

            optimized = numpy_safe(optimized)

            if 'text' in optimized and optimized.get('text'):
                optimized['text'] = clean_formatting(optimized.get('text', ''))

            # Save TXT
            txt_path = None
            if optimized.get('text'):
                txt_path = _save_text_file_and_get_path(
                    optimized['text'],
                    out_name="optimized_resume.txt"
                )
                optimized['txt_path'] = txt_path

            # Try PDF
            pdf_path = None
            try:
                candidate = optimized.get("pdf_path")
                if candidate and isinstance(candidate, str) and os.path.exists(candidate):
                    pdf_path = candidate
                else:
                    candidate2 = rewriter.generate_pdf(optimized, "professional")
                    if candidate2 and isinstance(candidate2, str) and os.path.exists(candidate2):
                        pdf_path = candidate2
                optimized['pdf_path'] = pdf_path
            except Exception:
                optimized['pdf_path'] = None

            st.session_state.optimized_resume = optimized

            # Save to DB
            try:
                save_analysis_to_db(
                    st.session_state.ats_scores,
                    parsed_resume=st.session_state.parsed_resume,
                    filename=st.session_state.parsed_resume.get("filename", "uploaded_resume.pdf"),
                    job_title=(st.session_state.job_description or "")[:120]
                )
            except Exception:
                pass

        st.success("Optimized resume generated!")

    # If already optimized, display editable blocks
    if st.session_state.get("optimized_resume"):
        opt = st.session_state.optimized_resume

        st.markdown("---")
        st.header("Full Optimized Text")
        st.text_area("Optimized Text", opt.get("text", ""), height=300)

        st.markdown("---")
        st.header("Section-wise Editable Blocks")

        sec_map = {
            "summary_optimized": "Summary",
            "experience_optimized": "Experience",
            "skills_optimized": "Skills",
            "education_optimized": "Education"
        }

        for key, label in sec_map.items():
            content = opt.get(key, "")
            if content:
                st.subheader(label)
                txt_key = f"opt_{key}"
                st.session_state[txt_key] = st.text_area(
                    label,
                    value=st.session_state.get(txt_key, content),
                    height=200,
                    key=txt_key
                )

                if st.button(f"Mark {label} for Copy", key=f"btn_copy_{key}"):
                    st.success(f"{label} ready — select and copy manually.")

        st.markdown("---")
        st.header("Downloads")

        # TXT Download
        if opt.get("txt_path") and os.path.exists(opt.get("txt_path")):
            with open(opt.get("txt_path"), "rb") as f:
                data = f.read()
            st.markdown(create_download_link_bytes(data, "optimized_resume.txt", label="Download TXT"), unsafe_allow_html=True)
        elif opt.get("text"):
            st.markdown(create_download_link_bytes(opt.get("text").encode("utf-8"), "optimized_resume.txt", label="Download TXT"), unsafe_allow_html=True)

        # PDF Download
        if opt.get("pdf_path") and os.path.exists(opt.get("pdf_path")):
            with open(opt.get("pdf_path"), "rb") as f:
                data = f.read()
            st.markdown(create_download_link_bytes(data, "optimized_resume.pdf", label="Download PDF"), unsafe_allow_html=True)
        else:
            st.info("PDF not generated.")

        st.markdown("---")
        st.header("Improvements Made")
        for imp in opt.get("improvements", []):
            st.write(f"- {imp}")


def page_dashboard():
    st.title("Analytics Dashboard")
    df = load_all_analysis()
    if df.empty:
        st.info("No analytics yet — analyze some resumes first.")
        return

    # sanitize
    if 'upload_date' in df.columns:
        df['upload_date'] = pd.to_datetime(df['upload_date'], errors='coerce')
    else:
        df['upload_date'] = pd.NaT
    df['ats_score'] = pd.to_numeric(df['ats_score'], errors='coerce')

    total = len(df)
    avg_ats = df['ats_score'].mean() if 'ats_score' in df else None
    high = int((df['ats_score'] >= 0.7).sum()) if 'ats_score' in df else 0
    recent = int(df[df['upload_date'] >= (pd.Timestamp.now() - pd.Timedelta(days=7))].shape[0]) if 'upload_date' in df else 0

    display_metric_row(total, avg_ats, high, recent)
    st.markdown("---")

    # Upload trend
    st.subheader("Upload Trend")
    if df['upload_date'].notna().any():
        upload_trend = df.groupby(df['upload_date'].dt.date).size().reset_index(name='count')
        fig = px.line(upload_trend, x='upload_date', y='count', title="Resumes Uploaded Over Time")
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("No timestamps to show upload trend.")

    # Score trend
    st.subheader("ATS Score Trend")
    if df['upload_date'].notna().any():
        score_trend = df.groupby(df['upload_date'].dt.date)['ats_score'].mean().reset_index()
        fig2 = px.line(score_trend, x='upload_date', y='ats_score', title="Avg ATS Score Over Time")
        st.plotly_chart(fig2, use_container_width=True)

    st.markdown("---")
    # Skills trend

    st.subheader("Top Skills")
    all_skills: List[str] = []
    if 'skills' in df.columns:
        for val in df['skills'].dropna():
            try:
                parsed = json.loads(val)
                if isinstance(parsed, list):
                    all_skills.extend(parsed)
            except Exception:
                # fallback: ignore
                pass

    # >>> REFACTORED: make skill plotting robust to Series names / empty data
    if all_skills:
        # create counts (Series indexed by skill)
        skill_counts = pd.Series(all_skills).value_counts().head(30)

        # Convert Series → DataFrame safely, handling different Series.name possibilities
        df_skills = skill_counts.reset_index()
        # df_skills columns now [<skill col name>, <count col name>], rename deterministically
        if df_skills.shape[1] >= 2:
            df_skills.columns = ["skill", "count"]
        else:
            # Defensive fallback
            df_skills = df_skills.rename(columns={df_skills.columns[0]: "skill"})
            df_skills["count"] = skill_counts.values

        # Final safety: ensure types
        df_skills["skill"] = df_skills["skill"].astype(str)
        df_skills["count"] = pd.to_numeric(df_skills["count"], errors='coerce').fillna(0).astype(int)

        # Create bar chart
        fig3 = px.bar(
            df_skills,
            x="skill",
            y="count",
            title="Most Common Skills",
        )
        st.plotly_chart(fig3, use_container_width=True)
    else:
        st.info("No skill data stored yet.")

    st.markdown("---")
    # per-job performance
    st.subheader("Per-job performance (by job_title or JD snippet)")
    if 'job_title' in df.columns:
        df['job_label'] = df['job_title'].fillna("(No job label)").astype(str)
        job_stats = df.groupby('job_label').agg(count=('id','count'), avg_ats=('ats_score','mean')).reset_index().sort_values('avg_ats', ascending=False)
        st.dataframe(job_stats.head(80), use_container_width=True)
    else:
        st.info("No job labels captured.")

    st.markdown("---")
    st.subheader("Recent Analyses")
    cols = ['filename','upload_date','ats_score','layout_score','thumbnail_path']
    preview_cols = [c for c in cols if c in df.columns]
    preview = df[preview_cols].head(12).copy()
    # format
    if 'ats_score' in preview:
        preview['ats_score'] = preview['ats_score'].apply(lambda x: f"{x:.1%}" if pd.notna(x) else "N/A")
    if 'layout_score' in preview:
        preview['layout_score'] = preview['layout_score'].apply(lambda x: f"{x:.1%}" if pd.notna(x) else "N/A")
    st.dataframe(preview, use_container_width=True)

# --------------------------- App main ----------------------------

def main():
    ensure_db()
    if 'page' not in st.session_state:
        st.session_state.page = "Upload"

    # Top header
    st.markdown("""
    <div style='display:flex;align-items:center;gap:18px'>
      <div style='background:linear-gradient(90deg,#7b39ff,#9f6bff);padding:12px;border-radius:10px;color:white;font-weight:800'>AI</div>
      <div>
        <div style='font-size:20px;font-weight:800'>Resume Analyzer — Simplified Optimize</div>
        <div style='color:#666'>Multigranularity • Multi-modal • ATS-ready</div>
      </div>
    </div>
    <hr />
    """, unsafe_allow_html=True)

    # Sidebar (modern)
    with st.sidebar:
        st.title("Navigation")
        st.markdown("Choose a workflow step")
        page = st.radio("", ["Upload", "Job Match", "Optimize", "Dashboard"], index=["Upload","Job Match","Optimize","Dashboard"].index(st.session_state.page if st.session_state.page in ["Upload","Job Match","Optimize","Dashboard"] else "Upload"))
        st.session_state.page = page
        st.markdown("---")
        st.markdown("Quick Stats")
        df = load_all_analysis()
        total = len(df)
        st.metric("Total Analyzed", total)
        if st.button("Clear Session State"):
            for k in list(st.session_state.keys()):
                del st.session_state[k]
            st.experimental_rerun()

    # page routing
    if st.session_state.page == "Upload":
        page_upload()
    elif st.session_state.page == "Job Match":
        page_job_matching()
    elif st.session_state.page == "Optimize":
        page_optimize()
    elif st.session_state.page == "Dashboard":
        page_dashboard()

if __name__ == "__main__":
    main()
